### ISSUE TITLE
Fix Cache not properly interacting with DESCRIPTION

### ISSUE THREAD

**Issue by mattangoh** [shaytran/footwrap#3]
inside of the .yml, we need to update the
``` 
    - name: Cache R packages
      uses: actions/cache@v2
      with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
```
It's not properly working.
